### PR TITLE
Added missing "TestAsset" files to make travis green

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
travis now green, should be merge-able now

**Comment by gianarb** [comment]
:+1:

**Comment by samsonasik** [comment]
@gianarb do you have access for merge ? :dancer:

**Comment by Maks3w** [comment]
This need to be discussed yet

**Comment by gianarb** [comment]
No @samsonasik :+1:

**Comment by Maks3w** [comment]
Thanks, but I rewrote the test removing the optional asset and changing the validator class.

**Pull request closed without merging**
