### PR TITLE
fix #106 PR problem (bug #121)

### PR DESCRIPTION
**Pull request by rwrz**
This PR should fix the bug #121 that was created after the PR #106

### CODE REVIEW

**Comment by rwrz** [comment]
@weierophinney could you please merge this one? This bug is extremely bad... any of my collections does the bind after the 2.9.0...

**Comment by weierophinney** [comment]
Thanks, @rwrz; released with 2.9.2 just now.

**Comment by rwrz** [comment]
Thank you! =)

**Comment by davidwindell** [comment]
Thanks @rwrz, not sure how tests weren't covering this one before!

**Pull request merged**
