### PR TITLE
Angular attribute support

### PR DESCRIPTION
**Pull request by pierrejochem**
Support for Angularjs attributes

### CODE REVIEW

**Comment by grizzm0** [comment]
We can't support every edge case out there. If you want to use angular attributes within the framework you could use data-ng-*.

**Comment by weierophinney** [comment]
Knowing that Angular attributes can be prefixed using either `ng-` or `data-ng-`, and that the latter *already works*, I'm inclined to close this, as doing so reduces maintenance on our part.

Thanks, however, for the effort put in!

**Comment by pierrejochem** [comment]
That doesn't work for all Attributes :-( but i have extended the view helper to allow these attributes. Angular is very spreaded so it is not just one Edge case. Cheers Pierre

**Comment by froschdesign** [comment]
> Angular is very spreaded so it is not just one Edge case.

On the other side: the `ng-` attributes are not valid HTML.

**Comment by grizzm0** [comment]
Mixing angular with backend rendered content is not **that** common either. Most people uses angular for SPA which is not rendered by the backend.

**Comment by pierrejochem** [comment]
That was just a proposal and I mix the technologies because I like the dynamic behavior of angular. You are both right!

**Pull request closed without merging**
